apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: apps
spec:
  acme:
    #The ACME server URL
    #server: https://acme-v02.api.letsencrypt.org/directory   #this link is for prod
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    #Email address used for ACME registration
    email: nenfl@yahoo.com
    #Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-sec-staging
    #Enable HTTP01 validations
    http01: {}
